# Generated by Django 3.2.7 on 2021-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmr', '0004_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hip_circum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist_circum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='vitals',
        ),
    ]
