# Generated by Django 3.2.7 on 2021-09-28 03:40

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pmr', '0005_auto_20210927_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='coffee',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexual_orientation',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surgery',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tobacco',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('year_started', models.CharField(blank=True, max_length=50, null=True)),
                ('year_stopped', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tobacco_profile', to='pmr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='sexual',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('abusement', models.CharField(blank=True, max_length=50, null=True)),
                ('abusement_status', jsonfield.fields.JSONField(blank=True, null=True)),
                ('sexual_status', jsonfield.fields.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sexual_profile', to='pmr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('year_started', models.CharField(blank=True, max_length=50, null=True)),
                ('year_stopped', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_profile', to='pmr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('year_of_education', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', jsonfield.fields.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_profile', to='pmr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='caffine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('year_started', models.CharField(blank=True, max_length=50, null=True)),
                ('year_stopped', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caffine_profile', to='pmr.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Alchol',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('year_started', models.CharField(blank=True, max_length=50, null=True)),
                ('year_stopped', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alchol_profile', to='pmr.profile')),
            ],
        ),
    ]
